package vdc;
/**
 *Definicion de los codigos a transmitir
 */
public enum ErrorCheck {
	VDC_NOT_COMPLETED,
	VLINK_NOT_COMPLETED,
	VM_NOT_COMPLETED,
	VNODE_NOT_COMPLETED,
	TENANTID_NOT_FOUND,
	VNODE_FROM_VLINK_WRONG,
	TENANTID_REQUIRED,
	BAD_CONTENT_TYPE,
	ALL_OK;
}
